FROM alpine:3.6

# Copy the current directory contents into the container at /app
ADD . /myForm/frontend
WORKDIR /myForm/frontend

# Install any needed packages specified in requirements.txt
RUN apk add --update py-pip  nodejs nodejs-npm
RUN npm install -g @angular/cli



# Make port 4200  available to the world outside this container
EXPOSE 4200

# Run app.py when the container launches
ENTRYPOINT ["ng"]
CMD ["serve", "-H", "0.0.0.0" ]

