version: "2"
services:
  backend:
    # replace username/repo:tag with your name and image details
    image: nadinepiveteau/backend:latest
    build: backend
    env_file: dev.env
    command:
      - python
      - app.py
      - "8000"
    ports:
      - "8000:8000"
  frontend:
    # replace username/repo:tag with your name and image details
    image: nadinepiveteau/frontend:latest
    build: frontend
    env_file: dev.env
    command:
      - npm
      - start
    ports:
      - "4200:4200"
    depends_on:
      - backend
