version: "3"
services:
  backend:
    # replace username/repo:tag with your name and image details
    image: nadinepiveteau/form:backend
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    networks:
      - webnet
  frontend: 
    # replace username/repo:tag with your name and image details
    image: nadinepiveteau/form:frontend
    deploy:
      replicas: 1 
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4200:4200"
    networks:
      - webnet

networks:
  webnet:
